/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/domain/Entity.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.chaouki.icc.reservations.domain;

import static javax.persistence.CascadeType.MERGE;
import static javax.persistence.CascadeType.PERSIST;
import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.validator.constraints.NotEmpty;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;
import com.jaxio.jpa.querybyexample.Identifiable;

@Entity
@Table(name = "artists")
public class Artists implements Identifiable<Integer>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = LoggerFactory.getLogger(Artists.class);

    // Raw attributes
    private Integer id;
    private String firstname;
    private String lastname;

    // Many to many
    private List<Types> types = new ArrayList<Types>();
    // -- [id] ------------------------

    @Override
    @Column(name = "id", precision = 10)
    @GeneratedValue(strategy = IDENTITY)
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public Artists id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [firstname] ------------------------

    @NotEmpty
    @Size(max = 60)
    @Column(name = "firstname", nullable = false, length = 60)
    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public Artists firstname(String firstname) {
        setFirstname(firstname);
        return this;
    }
    // -- [lastname] ------------------------

    @NotEmpty
    @Size(max = 60)
    @Column(name = "lastname", nullable = false, length = 60)
    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public Artists lastname(String lastname) {
        setLastname(lastname);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to Many
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
    // many-to-many: artists ==> types
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 

    /**
     * Returns the {@link #types} list.
     */
    @JoinTable(name = "artiste_type", joinColumns = @JoinColumn(name = "artist_id") , inverseJoinColumns = @JoinColumn(name = "type_id") )
    @ManyToMany(cascade = { PERSIST, MERGE })
    public List<Types> getTypes() {
        return types;
    }

    /**
     * Set the {@link #types} list.
     *
     * @param types the list of Types
     */
    public void setTypes(List<Types> types) {
        this.types = types;
    }

    /**
     * Helper method to add the passed {@link Types} to the {@link #types} list.
     */
    public boolean addType(Types type) {
        return getTypes().add(type);
    }

    /**
     * Helper method to remove the passed {@link Types} from the {@link #types} list.
     */
    public boolean removeType(Types type) {
        return getTypes().remove(type);
    }

    /**
     * Helper method to determine if the passed {@link Types} is present in the {@link #types} list.
     */
    public boolean containsType(Types type) {
        return getTypes() != null && getTypes().contains(type);
    }

    /**
     * Apply the default values.
     */
    public Artists withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Artists && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Artists instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("firstname", getFirstname()) //
                .add("lastname", getLastname()) //
                .toString();
    }
}