/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.chaouki.icc.reservations.domain;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Artists.class)
public abstract class Artists_ {

    // Raw attributes
    public static volatile SingularAttribute<Artists, Integer> id;
    public static volatile SingularAttribute<Artists, String> firstname;
    public static volatile SingularAttribute<Artists, String> lastname;

    // Many to many
    public static volatile ListAttribute<Artists, Types> types;
}