/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.chaouki.icc.reservations.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Locations.class)
public abstract class Locations_ {

    // Raw attributes
    public static volatile SingularAttribute<Locations, Integer> id;
    public static volatile SingularAttribute<Locations, String> slug;
    public static volatile SingularAttribute<Locations, String> designation;
    public static volatile SingularAttribute<Locations, String> address;
    public static volatile SingularAttribute<Locations, String> website;
    public static volatile SingularAttribute<Locations, String> phone;

    // Many to one
    public static volatile SingularAttribute<Locations, Localities> locality;
}