/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.chaouki.icc.reservations.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Shows.class)
public abstract class Shows_ {

    // Raw attributes
    public static volatile SingularAttribute<Shows, Integer> id;
    public static volatile SingularAttribute<Shows, String> slug;
    public static volatile SingularAttribute<Shows, String> title;
    public static volatile SingularAttribute<Shows, String> posterUrl;
    public static volatile SingularAttribute<Shows, Boolean> bookable;
    public static volatile SingularAttribute<Shows, Double> price;

    // Many to one
    public static volatile SingularAttribute<Shows, Category> category;
    public static volatile SingularAttribute<Shows, Locations> location;
}