/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/conversation/ConversationListener.p.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.chaouki.icc.reservations.web.conversation;

import javax.faces.lifecycle.Lifecycle;
import javax.servlet.http.HttpServletRequest;

/**
 * Interface to be implemented if you wish to listen to the {@link Lifecycle} of {@link Conversation conversations}.
 */
public interface ConversationListener {

    /**
     * Called after a {@link Conversation} has been created but before it starts.
     * @param conversation the conversation that was created.
     */
    void conversationCreated(Conversation conversation);

    /**
     * Called to indicate the passed conversation is being resumed.
     */
    void conversationResuming(Conversation conversation, HttpServletRequest request);

    /**
     * Called to indicate the passed Conversation is being paused.
     */
    void conversationPausing(Conversation conversation);

    /**
     * Called to indicate the conversation is ending.
     */
    void conversationEnding(Conversation conversation);
}