/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/conversation/ConversationHolder.p.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.chaouki.icc.reservations.web.conversation;

/**
 * Holds the current {@link Conversation} in the current thread of execution.
 */
public final class ConversationHolder {
    private static final ThreadLocal<Conversation> currentConversationHolder = new ThreadLocal<Conversation>();

    private ConversationHolder() {
    }

    /**
     * Returns the {@link Conversation} that is bound to the current thread of execution.
     */
    public static Conversation getCurrentConversation() {
        return currentConversationHolder.get();
    }

    /**
     * Bind the passed {@link Conversation} to the current thread of execution.
     */
    public static void setCurrentConversation(Conversation conversation) {
        currentConversationHolder.set(conversation);
    }
}