/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.chaouki.icc.reservations.web.dataimport;

import com.chaouki.icc.reservations.domain.Shows;
import com.chaouki.icc.reservations.service.ShowService;
import com.chaouki.icc.reservations.service.SpectacleProviderGateway;
import com.chaouki.icc.reservations.web.faces.ViewScoped;

import javax.inject.Inject;
import javax.inject.Named;
import java.io.Serializable;
import java.util.List;

@Named
@ViewScoped
public class LondonTheatreImportController implements Serializable {

    @Inject
    private SpectacleProviderGateway spectacleProviderGateway;

    @Inject
    private ShowService showService;

    private ShowDataModel shows;
    private List<Shows> selectedShows;

    public void fetchData() {
        List<Shows> showsList = spectacleProviderGateway.getShows();
        this.shows = new ShowDataModel(showsList);
    }

    public void importData() {
        System.out.println("Import data called. size: " + selectedShows.size());
        showService.importShows(selectedShows);
    }

    public ShowDataModel getShows() {
        return shows;
    }

    public void setShows(ShowDataModel shows) {
        this.shows = shows;
    }

    public List<Shows> getSelectedShows() {
        return selectedShows;
    }

    public void setSelectedShows(List<Shows> selectedShows) {
        this.selectedShows = selectedShows;
    }
}