/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.chaouki.icc.reservations.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.chaouki.icc.reservations.domain.Artists;
import com.chaouki.icc.reservations.web.domain.support.GenericExcelExporter;
import com.chaouki.icc.reservations.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link Artists} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class ArtistsExcelExporter extends GenericExcelExporter<Artists> {
    @Inject
    protected ArtistsSearchForm sf;

    public ArtistsExcelExporter() {
        super("artists_firstname", "artists_lastname");
    }

    @Override
    protected void fillResultItem(int row, Artists item) {
        int col = 0;
        setValue(row, col++, item.getFirstname());
        setValue(row, col++, item.getLastname());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setSelector(row++, 0, "artists_firstname", sf.getFirstnameSelector());
        setSelector(row++, 0, "artists_lastname", sf.getLastnameSelector());
        setSelectedEntities(row++, 0, "artists_types", sf.getArtists().getTypes());
    }
}