/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.chaouki.icc.reservations.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.chaouki.icc.reservations.domain.Artists;
import com.chaouki.icc.reservations.printer.ArtistsPrinter;
import com.chaouki.icc.reservations.repository.ArtistsRepository;
import com.chaouki.icc.reservations.web.domain.support.GenericController;
import com.chaouki.icc.reservations.web.permission.ArtistsPermission;

/**
 * Stateless controller for {@link Artists} conversation start.
 */
@Named
@Singleton
public class ArtistsController extends GenericController<Artists, Integer> {
    public static final String ARTISTS_EDIT_URI = "/domain/artistsEdit.faces";
    public static final String ARTISTS_SELECT_URI = "/domain/artistsSelect.faces";

    @Inject
    public ArtistsController(ArtistsRepository artistsRepository, ArtistsPermission artistsPermission, ArtistsPrinter artistsPrinter) {
        super(artistsRepository, artistsPermission, artistsPrinter, ARTISTS_SELECT_URI, ARTISTS_EDIT_URI);
    }
}