/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.chaouki.icc.reservations.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.chaouki.icc.reservations.domain.CastMember;
import com.chaouki.icc.reservations.printer.CastMemberPrinter;
import com.chaouki.icc.reservations.repository.CastMemberRepository;
import com.chaouki.icc.reservations.web.domain.support.GenericController;
import com.chaouki.icc.reservations.web.permission.CastMemberPermission;

/**
 * Stateless controller for {@link CastMember} conversation start.
 */
@Named
@Singleton
public class CastMemberController extends GenericController<CastMember, Integer> {
    public static final String CASTMEMBER_EDIT_URI = "/domain/castMemberEdit.faces";
    public static final String CASTMEMBER_SELECT_URI = "/domain/castMemberSelect.faces";

    @Inject
    public CastMemberController(CastMemberRepository castMemberRepository, CastMemberPermission castMemberPermission, CastMemberPrinter castMemberPrinter) {
        super(castMemberRepository, castMemberPermission, castMemberPrinter, CASTMEMBER_SELECT_URI, CASTMEMBER_EDIT_URI);
    }
}