/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.chaouki.icc.reservations.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.chaouki.icc.reservations.domain.Localities;
import com.chaouki.icc.reservations.domain.Localities_;
import com.chaouki.icc.reservations.printer.LocalitiesPrinter;
import com.chaouki.icc.reservations.repository.LocalitiesRepository;
import com.chaouki.icc.reservations.web.domain.support.GenericController;
import com.chaouki.icc.reservations.web.permission.LocalitiesPermission;
import com.jaxio.jpa.querybyexample.SearchParameters;

/**
 * Stateless controller for {@link Localities} conversation start.
 */
@Named
@Singleton
public class LocalitiesController extends GenericController<Localities, Integer> {
    public static final String LOCALITIES_EDIT_URI = "/domain/localitiesEdit.faces";
    public static final String LOCALITIES_SELECT_URI = "/domain/localitiesSelect.faces";

    @Inject
    public LocalitiesController(LocalitiesRepository localitiesRepository, LocalitiesPermission localitiesPermission, LocalitiesPrinter localitiesPrinter) {
        super(localitiesRepository, localitiesPermission, localitiesPrinter, LOCALITIES_SELECT_URI, LOCALITIES_EDIT_URI);
    }

    @Override
    protected SearchParameters defaultOrder(SearchParameters searchParameters) {
        return searchParameters.asc(Localities_.locality);
    }
}