/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.chaouki.icc.reservations.web.domain;

import static com.jaxio.jpa.querybyexample.PropertySelector.newPropertySelector;

import javax.inject.Named;

import com.chaouki.icc.reservations.domain.Localities;
import com.chaouki.icc.reservations.domain.Localities_;
import com.chaouki.icc.reservations.web.domain.support.GenericSearchForm;
import com.chaouki.icc.reservations.web.faces.ConversationContextScoped;
import com.jaxio.jpa.querybyexample.PropertySelector;
import com.jaxio.jpa.querybyexample.SearchParameters;

/**
 * View Helper to search {@link Localities}.
 * It exposes a {@link Localities} instance so it can be used in search by-example-query.
 */
@Named
@ConversationContextScoped
public class LocalitiesSearchForm extends GenericSearchForm<Localities, Integer, LocalitiesSearchForm> {
    private static final long serialVersionUID = 1L;
    protected Localities localities = new Localities();
    protected PropertySelector<Localities, String> postalCodeSelector = newPropertySelector(Localities_.postalCode);
    protected PropertySelector<Localities, String> localitySelector = newPropertySelector(Localities_.locality);

    public Localities getLocalities() {
        return localities;
    }

    @Override
    protected Localities getEntity() {
        return getLocalities();
    }

    @Override
    public LocalitiesSearchForm newInstance() {
        return new LocalitiesSearchForm();
    }

    @Override
    public SearchParameters toSearchParameters() {
        SearchParameters sp = searchParameters();
        sp.property(postalCodeSelector, localitySelector);
        return sp;
    }

    @Override
    public void resetWithOther(LocalitiesSearchForm other) {
        this.localities = other.getLocalities();
        this.postalCodeSelector = other.getPostalCodeSelector();
        this.localitySelector = other.getLocalitySelector();
    }

    // Property selectors
    public PropertySelector<Localities, String> getPostalCodeSelector() {
        return postalCodeSelector;
    }

    public PropertySelector<Localities, String> getLocalitySelector() {
        return localitySelector;
    }
}
