/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.chaouki.icc.reservations.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.model.LazyDataModel;

import com.chaouki.icc.reservations.domain.Locality;
import com.chaouki.icc.reservations.repository.LocalityRepository;
import com.chaouki.icc.reservations.web.domain.support.GenericLazyDataModel;
import com.chaouki.icc.reservations.web.faces.ConversationContextScoped;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link Locality}
 */
@Named
@ConversationContextScoped
public class LocalityLazyDataModel extends GenericLazyDataModel<Locality, Integer, LocalitySearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    public LocalityLazyDataModel(LocalityRepository localityRepository, LocalityController localityController, LocalitySearchForm localitySearchForm,
            LocalityExcelExporter localityExcelExporter) {
        super(localityRepository, localityController, localitySearchForm, localityExcelExporter);
    }
}