/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.chaouki.icc.reservations.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.chaouki.icc.reservations.domain.Locality;
import com.chaouki.icc.reservations.domain.Locality_;
import com.chaouki.icc.reservations.printer.LocalityPrinter;
import com.chaouki.icc.reservations.repository.LocalityRepository;
import com.chaouki.icc.reservations.web.domain.support.GenericController;
import com.chaouki.icc.reservations.web.permission.LocalityPermission;
import com.jaxio.jpa.querybyexample.SearchParameters;

/**
 * Stateless controller for {@link Locality} conversation start.
 */
@Named
@Singleton
public class LocalityController extends GenericController<Locality, Integer> {
    public static final String LOCALITY_EDIT_URI = "/domain/localityEdit.faces";
    public static final String LOCALITY_SELECT_URI = "/domain/localitySelect.faces";

    @Inject
    public LocalityController(LocalityRepository localityRepository, LocalityPermission localityPermission, LocalityPrinter localityPrinter) {
        super(localityRepository, localityPermission, localityPrinter, LOCALITY_SELECT_URI, LOCALITY_EDIT_URI);
    }

    @Override
    protected SearchParameters defaultOrder(SearchParameters searchParameters) {
        return searchParameters.asc(Locality_.locality2);
    }
}