/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/GraphLoader.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.chaouki.icc.reservations.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.chaouki.icc.reservations.domain.RepresentationUser;
import com.chaouki.icc.reservations.repository.RepresentationUserRepository;
import com.jaxio.jpa.querybyexample.EntityGraphLoader;

/**
 * Preloads the {@link RepresentationUser} associations required by the view layer.
 * 
 * Do not use other GraphLoaders in this GraphLoader. 
 */
@Named
@Singleton
public class RepresentationUserGraphLoader extends EntityGraphLoader<RepresentationUser, Integer> {
    // required by cglib to create a proxy around the object as we are using the @Transactional annotation
    protected RepresentationUserGraphLoader() {
        super();
    }

    @Inject
    public RepresentationUserGraphLoader(RepresentationUserRepository representationUserRepository) {
        super(representationUserRepository);
    }

    @Override
    public void loadGraph(RepresentationUser representationUser) {
        loadSingular(representationUser.getUser());
        loadSingular(representationUser.getRepresentation());
    }
}