/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.chaouki.icc.reservations.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.model.LazyDataModel;

import com.chaouki.icc.reservations.domain.RepresentationUser;
import com.chaouki.icc.reservations.repository.RepresentationUserRepository;
import com.chaouki.icc.reservations.web.domain.support.GenericLazyDataModel;
import com.chaouki.icc.reservations.web.faces.ConversationContextScoped;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link RepresentationUser}
 */
@Named
@ConversationContextScoped
public class RepresentationUserLazyDataModel extends GenericLazyDataModel<RepresentationUser, Integer, RepresentationUserSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    public RepresentationUserLazyDataModel(RepresentationUserRepository representationUserRepository, RepresentationUserController representationUserController,
            RepresentationUserSearchForm representationUserSearchForm, RepresentationUserExcelExporter representationUserExcelExporter) {
        super(representationUserRepository, representationUserController, representationUserSearchForm, representationUserExcelExporter);
    }
}