/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.chaouki.icc.reservations.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.chaouki.icc.reservations.domain.Representations;
import com.chaouki.icc.reservations.web.domain.support.GenericExcelExporter;
import com.chaouki.icc.reservations.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link Representations} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class RepresentationsExcelExporter extends GenericExcelExporter<Representations> {
    @Inject
    protected RepresentationsSearchForm sf;

    public RepresentationsExcelExporter() {
        super("representations_when");
    }

    @Override
    protected void fillResultItem(int row, Representations item) {
        int col = 0;
        setDateTime(row, col++, item.getWhen());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setSelectedEntities(row++, 0, "representations_show", sf.getShowSelector().getSelected());
        setRangeDateTime(row++, 0, "representations_when", sf.getWhenRange());
        setSelectedEntities(row++, 0, "representations_location", sf.getLocationSelector().getSelected());
    }
}