/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.chaouki.icc.reservations.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.chaouki.icc.reservations.domain.Representations;
import com.chaouki.icc.reservations.printer.RepresentationsPrinter;
import com.chaouki.icc.reservations.repository.RepresentationsRepository;
import com.chaouki.icc.reservations.web.domain.support.GenericController;
import com.chaouki.icc.reservations.web.permission.RepresentationsPermission;

/**
 * Stateless controller for {@link Representations} conversation start.
 */
@Named
@Singleton
public class RepresentationsController extends GenericController<Representations, Integer> {
    public static final String REPRESENTATIONS_EDIT_URI = "/domain/representationsEdit.faces";
    public static final String REPRESENTATIONS_SELECT_URI = "/domain/representationsSelect.faces";

    @Inject
    public RepresentationsController(RepresentationsRepository representationsRepository, RepresentationsPermission representationsPermission,
            RepresentationsPrinter representationsPrinter) {
        super(representationsRepository, representationsPermission, representationsPrinter, REPRESENTATIONS_SELECT_URI, REPRESENTATIONS_EDIT_URI);
    }
}