/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.chaouki.icc.reservations.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.chaouki.icc.reservations.domain.RepresentationUser;
import com.chaouki.icc.reservations.printer.RepresentationUserPrinter;
import com.chaouki.icc.reservations.repository.RepresentationUserRepository;
import com.chaouki.icc.reservations.web.domain.support.GenericController;
import com.chaouki.icc.reservations.web.permission.RepresentationUserPermission;

/**
 * Stateless controller for {@link RepresentationUser} conversation start.
 */
@Named
@Singleton
public class RepresentationUserController extends GenericController<RepresentationUser, Integer> {
    public static final String REPRESENTATIONUSER_EDIT_URI = "/domain/representationUserEdit.faces";
    public static final String REPRESENTATIONUSER_SELECT_URI = "/domain/representationUserSelect.faces";

    @Inject
    public RepresentationUserController(RepresentationUserRepository representationUserRepository, RepresentationUserPermission representationUserPermission,
            RepresentationUserPrinter representationUserPrinter) {
        super(representationUserRepository, representationUserPermission, representationUserPrinter, REPRESENTATIONUSER_SELECT_URI,
                REPRESENTATIONUSER_EDIT_URI);
    }
}