/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.chaouki.icc.reservations.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.chaouki.icc.reservations.domain.Roles;
import com.chaouki.icc.reservations.web.domain.support.GenericExcelExporter;
import com.chaouki.icc.reservations.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link Roles} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class RolesExcelExporter extends GenericExcelExporter<Roles> {
    @Inject
    protected RolesSearchForm sf;

    public RolesExcelExporter() {
        super("roles_role");
    }

    @Override
    protected void fillResultItem(int row, Roles item) {
        int col = 0;
        setValue(row, col++, item.getRole());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setSelector(row++, 0, "roles_role", sf.getRoleSelector());
    }
}