/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.chaouki.icc.reservations.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.chaouki.icc.reservations.domain.Roles;
import com.chaouki.icc.reservations.printer.RolesPrinter;
import com.chaouki.icc.reservations.repository.RolesRepository;
import com.chaouki.icc.reservations.web.domain.support.GenericController;
import com.chaouki.icc.reservations.web.permission.RolesPermission;

/**
 * Stateless controller for {@link Roles} conversation start.
 */
@Named
@Singleton
public class RolesController extends GenericController<Roles, Integer> {
    public static final String ROLES_EDIT_URI = "/domain/rolesEdit.faces";
    public static final String ROLES_SELECT_URI = "/domain/rolesSelect.faces";

    @Inject
    public RolesController(RolesRepository rolesRepository, RolesPermission rolesPermission, RolesPrinter rolesPrinter) {
        super(rolesRepository, rolesPermission, rolesPrinter, ROLES_SELECT_URI, ROLES_EDIT_URI);
    }
}