/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.chaouki.icc.reservations.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.chaouki.icc.reservations.domain.Shows;
import com.chaouki.icc.reservations.web.domain.support.GenericExcelExporter;
import com.chaouki.icc.reservations.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link Shows} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class ShowsExcelExporter extends GenericExcelExporter<Shows> {
    @Inject
    protected ShowsSearchForm sf;

    public ShowsExcelExporter() {
        super("shows_slug", "shows_title", "shows_posterUrl", "shows_bookable", "shows_price");
    }

    @Override
    protected void fillResultItem(int row, Shows item) {
        int col = 0;
        setValue(row, col++, item.getSlug());
        setValue(row, col++, item.getTitle());
        setValue(row, col++, item.getPosterUrl());
        setValue(row, col++, item.getBookable());
        setValue(row, col++, item.getPrice());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setSelector(row++, 0, "shows_slug", sf.getSlugSelector());
        setSelector(row++, 0, "shows_title", sf.getTitleSelector());
        setSelector(row++, 0, "shows_posterUrl", sf.getPosterUrlSelector());
        setSelectedEntities(row++, 0, "shows_location", sf.getLocationSelector().getSelected());
        setSelector(row++, 0, "shows_bookable", sf.getBookableSelector());
        setRangeNumber(row++, 0, "shows_price", sf.getPriceRange());
    }
}