/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.chaouki.icc.reservations.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.chaouki.icc.reservations.domain.Shows;
import com.chaouki.icc.reservations.domain.Shows_;
import com.chaouki.icc.reservations.printer.ShowsPrinter;
import com.chaouki.icc.reservations.repository.ShowsRepository;
import com.chaouki.icc.reservations.web.domain.support.GenericController;
import com.chaouki.icc.reservations.web.permission.ShowsPermission;
import com.jaxio.jpa.querybyexample.SearchParameters;

/**
 * Stateless controller for {@link Shows} conversation start.
 */
@Named
@Singleton
public class ShowsController extends GenericController<Shows, Integer> {
    public static final String SHOWS_EDIT_URI = "/domain/showsEdit.faces";
    public static final String SHOWS_SELECT_URI = "/domain/showsSelect.faces";

    @Inject
    public ShowsController(ShowsRepository showsRepository, ShowsPermission showsPermission, ShowsPrinter showsPrinter) {
        super(showsRepository, showsPermission, showsPrinter, SHOWS_SELECT_URI, SHOWS_EDIT_URI);
    }

    @Override
    protected SearchParameters defaultOrder(SearchParameters searchParameters) {
        return searchParameters.asc(Shows_.slug);
    }
}