/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.chaouki.icc.reservations.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.model.LazyDataModel;

import com.chaouki.icc.reservations.domain.Shows;
import com.chaouki.icc.reservations.repository.ShowsRepository;
import com.chaouki.icc.reservations.web.domain.support.GenericLazyDataModel;
import com.chaouki.icc.reservations.web.faces.ConversationContextScoped;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link Shows}
 */
@Named
@ConversationContextScoped
public class ShowsLazyDataModel extends GenericLazyDataModel<Shows, Integer, ShowsSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    public ShowsLazyDataModel(ShowsRepository showsRepository, ShowsController showsController, ShowsSearchForm showsSearchForm,
            ShowsExcelExporter showsExcelExporter) {
        super(showsRepository, showsController, showsSearchForm, showsExcelExporter);
    }
}