/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.chaouki.icc.reservations.web.domain;

import javax.annotation.PostConstruct;
import javax.inject.Inject;
import javax.inject.Named;
import javax.validation.constraints.NotNull;

import com.chaouki.icc.reservations.domain.Category;
import com.chaouki.icc.reservations.domain.Locations;
import com.chaouki.icc.reservations.domain.Shows;
import com.chaouki.icc.reservations.domain.Shows_;
import com.chaouki.icc.reservations.repository.ShowsRepository;
import com.chaouki.icc.reservations.web.domain.support.GenericEditForm;
import com.chaouki.icc.reservations.web.domain.support.GenericToOneAssociation;
import com.chaouki.icc.reservations.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link Shows}.
 */
@Named
@ConversationContextScoped
public class ShowsEditForm extends GenericEditForm<Shows, Integer> {
    @Inject
    protected ShowsController showsController;
    @Inject
    protected CategoryController categoryController;
    protected GenericToOneAssociation<Category, Integer> category;
    @Inject
    protected LocationsController locationsController;
    protected GenericToOneAssociation<Locations, Integer> location;

    @Inject
    public ShowsEditForm(ShowsRepository showsRepository, ShowsGraphLoader showsGraphLoader) {
        super(showsRepository, showsGraphLoader);
    }

    /**
     * The entity to edit/view.
     */
    public Shows getShows() {
        return getEntity();
    }

    public String print() {
        return showsController.print(getShows());
    }

    @PostConstruct
    void setupCategoryActions() {
        category = new GenericToOneAssociation<Category, Integer>(categoryController, Shows_.category) {
            @Override
            protected Category get() {
                return getShows().getCategory();
            }

            @Override
            protected void set(Category category) {
                getShows().setCategory(category);
            }
        };
    }

    public GenericToOneAssociation<Category, Integer> getCategory() {
        return category;
    }

    @PostConstruct
    void setupLocationActions() {
        location = new GenericToOneAssociation<Locations, Integer>(locationsController, Shows_.location) {
            @Override
            protected Locations get() {
                return getShows().getLocation();
            }

            @Override
            protected void set(Locations locations) {
                getShows().setLocation(locations);
            }

            @NotNull
            @Override
            public Locations getSelected() {
                return super.getSelected();
            }
        };
    }

    public GenericToOneAssociation<Locations, Integer> getLocation() {
        return location;
    }
}
