/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.chaouki.icc.reservations.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.model.LazyDataModel;

import com.chaouki.icc.reservations.domain.Types;
import com.chaouki.icc.reservations.repository.TypesRepository;
import com.chaouki.icc.reservations.web.domain.support.GenericLazyDataModel;
import com.chaouki.icc.reservations.web.faces.ConversationContextScoped;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link Types}
 */
@Named
@ConversationContextScoped
public class TypesLazyDataModel extends GenericLazyDataModel<Types, Integer, TypesSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    public TypesLazyDataModel(TypesRepository typesRepository, TypesController typesController, TypesSearchForm typesSearchForm,
            TypesExcelExporter typesExcelExporter) {
        super(typesRepository, typesController, typesSearchForm, typesExcelExporter);
    }
}