/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.chaouki.icc.reservations.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.chaouki.icc.reservations.domain.Types;
import com.chaouki.icc.reservations.printer.TypesPrinter;
import com.chaouki.icc.reservations.repository.TypesRepository;
import com.chaouki.icc.reservations.web.domain.support.GenericController;
import com.chaouki.icc.reservations.web.permission.TypesPermission;

/**
 * Stateless controller for {@link Types} conversation start.
 */
@Named
@Singleton
public class TypesController extends GenericController<Types, Integer> {
    public static final String TYPES_EDIT_URI = "/domain/typesEdit.faces";
    public static final String TYPES_SELECT_URI = "/domain/typesSelect.faces";

    @Inject
    public TypesController(TypesRepository typesRepository, TypesPermission typesPermission, TypesPrinter typesPrinter) {
        super(typesRepository, typesPermission, typesPrinter, TYPES_SELECT_URI, TYPES_EDIT_URI);
    }
}