/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.chaouki.icc.reservations.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.chaouki.icc.reservations.domain.Users;
import com.chaouki.icc.reservations.printer.UsersPrinter;
import com.chaouki.icc.reservations.repository.UsersRepository;
import com.chaouki.icc.reservations.web.domain.support.GenericController;
import com.chaouki.icc.reservations.web.permission.UsersPermission;

/**
 * Stateless controller for {@link Users} conversation start.
 */
@Named
@Singleton
public class UsersController extends GenericController<Users, Integer> {
    public static final String USERS_EDIT_URI = "/domain/usersEdit.faces";
    public static final String USERS_SELECT_URI = "/domain/usersSelect.faces";

    @Inject
    public UsersController(UsersRepository usersRepository, UsersPermission usersPermission, UsersPrinter usersPrinter) {
        super(usersRepository, usersPermission, usersPrinter, USERS_SELECT_URI, USERS_EDIT_URI);
    }
}