/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/services/ConcurrentModificationResolver.p.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.chaouki.icc.reservations.web.service;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.chaouki.icc.reservations.web.conversation.ConversationManager;

/**
 * Simple service used from the concurrentModificationResolution.xhtml view.
 */
@Named
@Singleton
public class ConcurrentModificationResolver {

    @Inject
    private ConversationManager conversationManager;

    public String refresh() {
        return conversationManager.getCurrentConversation().getCurrentContext().getCallBack().ok(null);
    }

    public String discard() {
        conversationManager.endCurrentConversation();
        return "/home.faces?faces-redirect=true";
    }
}