/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.chaouki.icc.reservations.repository;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.chaouki.icc.reservations.domain.Artists;
import com.chaouki.icc.reservations.domain.CastMember;
import com.chaouki.icc.reservations.domain.Shows;
import com.chaouki.icc.reservations.domain.Types;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class CastMemberGenerator {

    /**
     * Returns a new CastMember instance filled with random values.
     */
    public CastMember getCastMember() {
        CastMember castMember = new CastMember();

        // mandatory relation
        Artists artist = artistsGenerator.getArtists();
        artistsRepository.save(artist);
        castMember.setArtist(artist);
        // mandatory relation
        Types type = typesGenerator.getTypes();
        typesRepository.save(type);
        castMember.setType(type);
        // mandatory relation
        Shows show = showsGenerator.getShows();
        showsRepository.save(show);
        castMember.setShow(show);
        return castMember;
    }

    @Inject
    private ArtistsRepository artistsRepository;
    @Inject
    private ArtistsGenerator artistsGenerator;
    @Inject
    private TypesRepository typesRepository;
    @Inject
    private TypesGenerator typesGenerator;
    @Inject
    private ShowsRepository showsRepository;
    @Inject
    private ShowsGenerator showsGenerator;
}