/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.chaouki.icc.reservations.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import com.chaouki.icc.reservations.domain.Localities;
import com.chaouki.icc.reservations.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class LocalitiesGenerator {

    /**
     * Returns a new Localities instance filled with random values.
     */
    public Localities getLocalities() {
        Localities localities = new Localities();

        // simple attributes follows
        localities.setPostalCode(ValueGenerator.getUniqueString(6));
        localities.setLocality(ValueGenerator.getUniqueString(60));
        return localities;
    }

}