/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/RepositoryIT.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.chaouki.icc.reservations.repository;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.assertThat;

import java.util.List;
import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.chaouki.icc.reservations.domain.Representations;
import com.chaouki.icc.reservations.domain.Representations_;
import com.jaxio.jpa.querybyexample.SearchParameters;

/**
 * Integration test on RepresentationsRepository
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class RepresentationsRepositoryIT {
    @SuppressWarnings("unused")
    private static final Logger log = LoggerFactory.getLogger(RepresentationsRepositoryIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private RepresentationsRepository representationsRepository;

    @Inject
    private RepresentationsGenerator representationsGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        Representations representations = representationsGenerator.getRepresentations();

        // add it to a Set before saving (force equals/hashcode)
        Set<Representations> set = newHashSet(representations, representations);
        assertThat(set).hasSize(1);

        representationsRepository.save(representations);
        entityManager.flush();

        // reload it from cache and check equality
        Representations model = new Representations();
        model.setId(representations.getId());
        assertThat(representations).isEqualTo(representationsRepository.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(representations.getId()).isEqualTo(representationsRepository.get(model).getId());

        // but since you do not use a business key, equality is lost.
        assertThat(representations).isNotEqualTo(representationsRepository.get(model));
    }

    @Test
    @Rollback
    public void saveAndGetWithExplicitNullPropertySelector() {
        Representations representations = representationsGenerator.getRepresentations();

        // add it to a Set before saving (force equals/hashcode)
        Set<Representations> set = newHashSet(representations, representations);
        assertThat(set).hasSize(1);

        // explicitly set toOne relationship to null
        representations.setLocation(null);

        representationsRepository.save(representations);
        entityManager.flush();

        // clear cache to force reload from db
        entityManager.clear();

        SearchParameters searchParameters = new SearchParameters() //
                .caseInsensitive() //
                .anywhere() //
                .property(Representations_.location, (Object) null);

        List<Representations> elements = representationsRepository.find(searchParameters);
        assertThat(elements).isNotEmpty();
        for (Representations element : elements) {
            assertThat(element.getLocation()).isNull();
        }
    }
}