/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/RepositoryIT.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.chaouki.icc.reservations.repository;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.assertThat;

import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.chaouki.icc.reservations.domain.RepresentationUser;

/**
 * Integration test on RepresentationUserRepository
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class RepresentationUserRepositoryIT {
    @SuppressWarnings("unused")
    private static final Logger log = LoggerFactory.getLogger(RepresentationUserRepositoryIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private RepresentationUserRepository representationUserRepository;

    @Inject
    private RepresentationUserGenerator representationUserGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        RepresentationUser representationUser = representationUserGenerator.getRepresentationUser();

        // add it to a Set before saving (force equals/hashcode)
        Set<RepresentationUser> set = newHashSet(representationUser, representationUser);
        assertThat(set).hasSize(1);

        representationUserRepository.save(representationUser);
        entityManager.flush();

        // reload it from cache and check equality
        RepresentationUser model = new RepresentationUser();
        model.setId(representationUser.getId());
        assertThat(representationUser).isEqualTo(representationUserRepository.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(representationUser.getId()).isEqualTo(representationUserRepository.get(model).getId());

        // but since you do not use a business key, equality is lost.
        assertThat(representationUser).isNotEqualTo(representationUserRepository.get(model));
    }

}