/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.chaouki.icc.reservations.repository;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.chaouki.icc.reservations.domain.RepresentationUser;
import com.chaouki.icc.reservations.domain.Representations;
import com.chaouki.icc.reservations.domain.Users;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class RepresentationUserGenerator {

    /**
     * Returns a new RepresentationUser instance filled with random values.
     */
    public RepresentationUser getRepresentationUser() {
        RepresentationUser representationUser = new RepresentationUser();

        // simple attributes follows
        representationUser.setPlaces(1);
        // mandatory relation
        Users user = usersGenerator.getUsers();
        usersRepository.save(user);
        representationUser.setUser(user);
        // mandatory relation
        Representations representation = representationsGenerator.getRepresentations();
        representationsRepository.save(representation);
        representationUser.setRepresentation(representation);
        return representationUser;
    }

    @Inject
    private UsersRepository usersRepository;
    @Inject
    private UsersGenerator usersGenerator;
    @Inject
    private RepresentationsRepository representationsRepository;
    @Inject
    private RepresentationsGenerator representationsGenerator;
}