/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/RepositoryIT.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.chaouki.icc.reservations.repository;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.assertThat;

import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.chaouki.icc.reservations.domain.Roles;

/**
 * Integration test on RolesRepository
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class RolesRepositoryIT {
    @SuppressWarnings("unused")
    private static final Logger log = LoggerFactory.getLogger(RolesRepositoryIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private RolesRepository rolesRepository;

    @Inject
    private RolesGenerator rolesGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        Roles roles = rolesGenerator.getRoles();

        // add it to a Set before saving (force equals/hashcode)
        Set<Roles> set = newHashSet(roles, roles);
        assertThat(set).hasSize(1);

        rolesRepository.save(roles);
        entityManager.flush();

        // reload it from cache and check equality
        Roles model = new Roles();
        model.setId(roles.getId());
        assertThat(roles).isEqualTo(rolesRepository.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(roles.getId()).isEqualTo(rolesRepository.get(model).getId());

        // but since you do not use a business key, equality is lost.
        assertThat(roles).isNotEqualTo(rolesRepository.get(model));
    }

}