/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.chaouki.icc.reservations.repository;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.chaouki.icc.reservations.domain.Locations;
import com.chaouki.icc.reservations.domain.Shows;
import com.chaouki.icc.reservations.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class ShowsGenerator {

    /**
     * Returns a new Shows instance filled with random values.
     */
    public Shows getShows() {
        Shows shows = new Shows();

        // simple attributes follows
        shows.setSlug(ValueGenerator.getUniqueString(60));
        shows.setTitle("a");
        shows.setPosterUrl("http://www.jaxio.com");
        shows.setBookable(true);
        shows.setPrice(1d);
        // mandatory relation
        Locations location = locationsGenerator.getLocations();
        locationsRepository.save(location);
        shows.setLocation(location);
        return shows;
    }

    @Inject
    private LocationsRepository locationsRepository;
    @Inject
    private LocationsGenerator locationsGenerator;
}