/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.chaouki.icc.reservations.repository;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.chaouki.icc.reservations.domain.Roles;
import com.chaouki.icc.reservations.domain.Users;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class UsersGenerator {

    /**
     * Returns a new Users instance filled with random values.
     */
    public Users getUsers() {
        Users users = new Users();

        // simple attributes follows
        users.setLogin("a");
        users.setPassword("a");
        users.setFirstname("a");
        users.setLastname("a");
        users.setEmail("dummy@dummy.com");
        users.setLangue("a");
        // mandatory relation
        Roles role = rolesGenerator.getRoles();
        rolesRepository.save(role);
        users.setRole(role);
        return users;
    }

    @Inject
    private RolesRepository rolesRepository;
    @Inject
    private RolesGenerator rolesGenerator;
}