/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/RepositoryIT.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.chaouki.icc.reservations.repository;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.assertThat;

import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.chaouki.icc.reservations.domain.Users;

/**
 * Integration test on UsersRepository
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class UsersRepositoryIT {
    @SuppressWarnings("unused")
    private static final Logger log = LoggerFactory.getLogger(UsersRepositoryIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private UsersRepository usersRepository;

    @Inject
    private UsersGenerator usersGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        Users users = usersGenerator.getUsers();

        // add it to a Set before saving (force equals/hashcode)
        Set<Users> set = newHashSet(users, users);
        assertThat(set).hasSize(1);

        usersRepository.save(users);
        entityManager.flush();

        // reload it from cache and check equality
        Users model = new Users();
        model.setId(users.getId());
        assertThat(users).isEqualTo(usersRepository.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(users.getId()).isEqualTo(usersRepository.get(model).getId());

        // but since you do not use a business key, equality is lost.
        assertThat(users).isNotEqualTo(usersRepository.get(model));
    }

}