/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.chaouki.icc.reservations.domain;

import static org.fest.assertions.Assertions.assertThat;

import java.io.*;
import java.util.*;

import org.junit.Test;

import com.chaouki.icc.reservations.util.ValueGenerator;

/**
 * Basic tests for Representations
 */
@SuppressWarnings("unused")
public class RepresentationsTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        Representations model = new Representations();
        assertThat(model.isIdSet()).isFalse();
    }

    @Test
    public void isIdSetReturnsTrue() {
        Representations model = new Representations();
        model.setId(ValueGenerator.getUniqueInteger());
        assertThat(model.getId()).isNotNull();
        assertThat(model.isIdSet()).isTrue();
    }

    //-------------------------------------------------------------
    // Many to One:  Representations.show ==> Shows.id
    //-------------------------------------------------------------

    @Test
    public void manyToOne_setShow() {
        Representations many = new Representations();

        // init
        Shows one = new Shows();
        one.setId(ValueGenerator.getUniqueInteger());
        many.setShow(one);

        // make sure it is propagated properly
        assertThat(many.getShow()).isEqualTo(one);

        // now set it to back to null
        many.setShow(null);

        // make sure null is propagated properly
        assertThat(many.getShow()).isNull();
    }

    @Test
    public void manyToOne_setLocation() {
        Representations many = new Representations();

        // init
        Locations one = new Locations();
        one.setId(ValueGenerator.getUniqueInteger());
        many.setLocation(one);

        // make sure it is propagated properly
        assertThat(many.getLocation()).isEqualTo(one);

        // now set it to back to null
        many.setLocation(null);

        // make sure null is propagated properly
        assertThat(many.getLocation()).isNull();
    }

    /*
    public void equalsUsingPk() {
        Representations model1 = new Representations();
        Representations model2 = new Representations();
    
        Integer id = ValueGenerator.getUniqueInteger();
        model1.setId(id);
        model2.setId(id);
    
        model1.setWhen(new Date());
        model2.setWhen(new Date());
        assertThat(model1.isIdSet()).isTrue();
        assertThat(model2.isIdSet()).isTrue();
        assertThat(model1.hashCode()).isEqualTo(model2.hashCode());
        assertThat(model1).isEqualTo(model2);
        assertThat(model2).isEqualTo(model1);
    }
     */
}