/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.chaouki.icc.reservations.domain;

import static org.fest.assertions.Assertions.assertThat;

import java.io.*;
import java.util.*;

import org.junit.Test;

import com.chaouki.icc.reservations.util.ValueGenerator;

/**
 * Basic tests for Users
 */
@SuppressWarnings("unused")
public class UsersTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        Users model = new Users();
        assertThat(model.isIdSet()).isFalse();
    }

    @Test
    public void isIdSetReturnsTrue() {
        Users model = new Users();
        model.setId(ValueGenerator.getUniqueInteger());
        assertThat(model.getId()).isNotNull();
        assertThat(model.isIdSet()).isTrue();
    }

    //-------------------------------------------------------------
    // Many to One:  Users.role ==> Roles.id
    //-------------------------------------------------------------

    @Test
    public void manyToOne_setRole() {
        Users many = new Users();

        // init
        Roles one = new Roles();
        one.setId(ValueGenerator.getUniqueInteger());
        many.setRole(one);

        // make sure it is propagated properly
        assertThat(many.getRole()).isEqualTo(one);

        // now set it to back to null
        many.setRole(null);

        // make sure null is propagated properly
        assertThat(many.getRole()).isNull();
    }

    /*
    public void equalsUsingPk() {
        Users model1 = new Users();
        Users model2 = new Users();
    
        Integer id = ValueGenerator.getUniqueInteger();
        model1.setId(id);
        model2.setId(id);
    
        model1.setLogin("a");
        model2.setLogin("a");
    
        model1.setPassword("a");
        model2.setPassword("a");
    
        model1.setFirstname("a");
        model2.setFirstname("a");
    
        model1.setLastname("a");
        model2.setLastname("a");
    
        model1.setEmail("dummy@dummy.com");
        model2.setEmail("dummy@dummy.com");
    
        model1.setLangue("a");
        model2.setLangue("a");
        assertThat(model1.isIdSet()).isTrue();
        assertThat(model2.isIdSet()).isTrue();
        assertThat(model1.hashCode()).isEqualTo(model2.hashCode());
        assertThat(model1).isEqualTo(model2);
        assertThat(model2).isEqualTo(model1);
    }
     */
}