/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/repository/Repository.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.chaouki.icc.reservations.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import org.springframework.transaction.annotation.Transactional;

import com.chaouki.icc.reservations.domain.Locations;
import com.jaxio.jpa.querybyexample.GenericRepository;

/**
 * {@link GenericRepository} for {@link Locations} 
 */
@Named
@Singleton
public class LocationsRepository extends GenericRepository<Locations, Integer> {

    public LocationsRepository() {
        super(Locations.class);
    }

    @Override
    public Locations getNew() {
        return new Locations();
    }

    @Override
    public Locations getNewWithDefaults() {
        return getNew().withDefaults();
    }

    /**
     * Return the persistent instance of {@link Locations} with the given unique property value slug,
     * or null if there is no such persistent instance.
     *
     * @param slug the unique value
     * @return the corresponding {@link Locations} persistent instance or null
     */
    @Transactional(readOnly = true)
    public Locations getBySlug(String slug) {
        return findUniqueOrNone(new Locations().slug(slug));
    }

    /**
     * Delete a {@link Locations} using the unique column slug
     *
     * @param slug the unique value
     */
    @Transactional
    public void deleteBySlug(String slug) {
        delete(getBySlug(slug));
    }
}