/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/repository/Repository.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.chaouki.icc.reservations.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import com.chaouki.icc.reservations.domain.Types;
import com.jaxio.jpa.querybyexample.GenericRepository;

/**
 * {@link GenericRepository} for {@link Types} 
 */
@Named
@Singleton
public class TypesRepository extends GenericRepository<Types, Integer> {

    public TypesRepository() {
        super(Types.class);
    }

    @Override
    public Types getNew() {
        return new Types();
    }

    @Override
    public Types getNewWithDefaults() {
        return getNew().withDefaults();
    }
}