/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/repository/Repository.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.chaouki.icc.reservations.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import com.chaouki.icc.reservations.domain.Users;
import com.jaxio.jpa.querybyexample.GenericRepository;

/**
 * {@link GenericRepository} for {@link Users} 
 */
@Named
@Singleton
public class UsersRepository extends GenericRepository<Users, Integer> {

    public UsersRepository() {
        super(Users.class);
    }

    @Override
    public Users getNew() {
        return new Users();
    }

    @Override
    public Users getNewWithDefaults() {
        return getNew().withDefaults();
    }
}