/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/printer/Printer.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.chaouki.icc.reservations.printer;

import java.util.Locale;

import javax.inject.Named;
import javax.inject.Singleton;

import com.chaouki.icc.reservations.domain.RepresentationUser;
import com.chaouki.icc.reservations.domain.RepresentationUser_;
import com.chaouki.icc.reservations.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link RepresentationUser} 
 *
 * @see GenericPrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class RepresentationUserPrinter extends GenericPrinter<RepresentationUser> {
    public RepresentationUserPrinter() {
        super(RepresentationUser.class, RepresentationUser_.places);
    }

    @Override
    public String print(RepresentationUser representationUser, Locale locale) {
        if (representationUser == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, representationUser.getPlaces());
        return ret.toString();
    }
}