/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/printer/Printer.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.chaouki.icc.reservations.printer;

import java.util.Locale;

import javax.inject.Named;
import javax.inject.Singleton;

import com.chaouki.icc.reservations.domain.Types;
import com.chaouki.icc.reservations.domain.Types_;
import com.chaouki.icc.reservations.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link Types} 
 *
 * @see GenericPrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class TypesPrinter extends GenericPrinter<Types> {
    public TypesPrinter() {
        super(Types.class, Types_.type);
    }

    @Override
    public String print(Types types, Locale locale) {
        if (types == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, types.getType());
        return ret.toString();
    }
}