/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/util/IntegrationSampleIT.p.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.chaouki.icc.reservations.util;

import static org.fest.assertions.Assertions.assertThat;

import org.junit.Test;

/**
 * Integration test executed by FailSafe plugin
 */
public class IntegrationSampleIT {
    @Test
    public void executedByFailSafePlugin() {
        assertThat(true).isTrue();
    }
}