/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/faces/ConversationScope.p.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.chaouki.icc.reservations.web.faces;

import static com.chaouki.icc.reservations.web.conversation.ConversationHolder.getCurrentConversation;

import org.springframework.beans.factory.ObjectFactory;
import org.springframework.beans.factory.config.Scope;

import com.chaouki.icc.reservations.web.conversation.Conversation;

/**
 * Beans in the conversation scope reside in a {@link Conversation conversation}.
 * They are 'visible' only when the conversation is bound to the current thread of execution.
 */
public class ConversationScope implements Scope {

    @Override
    public String getConversationId() {
        return getCurrentConversation().getId();
    }

    @Override
    public Object get(String name, ObjectFactory<?> objectFactory) {
        Conversation currentConversation = getCurrentConversation();
        Object bean = currentConversation.getBean(name);

        if (bean == null) {
            bean = objectFactory.getObject();
            currentConversation.addBean(name, bean);
        }

        return bean;
    }

    @Override
    public Object remove(String name) {
        throw new UnsupportedOperationException("remove is done during conversation.end");
    }

    @Override
    public void registerDestructionCallback(String name, Runnable callback) {
        // no ops
    }

    @Override
    public Object resolveContextualObject(String key) {
        // TODO: is it really required?      
        throw new UnsupportedOperationException("remove is done during conversation.end");
    }
}